services:
#    entrada.example:
#        class: EntradaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     entradas.ultimas_entradas:
         class: EntradaBundle\Model\UltimasEntradas
         arguments: ["@doctrine.orm.entity_manager"]