user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /



entrada:
    path:      /entrada/{page}
    defaults:  { _controller: EntradaBundle:Entrada:show }

autores:
    path:      /autores/create
    defaults:  { _controller: EntradaBundle:Autor:create }
    
entradas:
    path:      /entradas/create
    defaults:  { _controller: EntradaBundle:Entrada:create }
entrada_homepage:
    path:     /entradas
    defaults: { _controller: EntradaBundle:Entrada:ultimasEntradas }
    
app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
  path: /login
  defaults: { _controller: EntradaBundle:Security:login }
  
logout:
  path: /logout
  
users_create:
  path: /users/create
  defaults: { _controller: UserBundle:Default:create }
    
    
