EntradaBundle\Entity\Autor:

oneToMany:
  enntradas:
    targetEntity: Entrada
    mappedBy: autor
  type: entity
  table: autores
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    nombre: 
      type: string
      length: 255
    nick:
      type: text