EntradaBundle\Entity\Entrada:
  type: entity
  table: entrada
  manyToOne:
    autor:
      inversedBy: entrada      
      targetEntity: Autor
      joinColumn: 
        name: autor_id
        referencedColumnName: id
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    titulo: 
      type: text
    descripcion:
      type: text